_BASE_: "./Base-BoundaryFormer-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  ROI_MASK_HEAD:
    NAME: "BoundaryFormerPolygonHead"
    POOLER_TYPE: ""
  BOUNDARY_HEAD:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    PRED_WITHIN_BOX: True
    POLY_NUM_PTS: 64
    CLS_AGNOSTIC_MASK: True
  DIFFRAS:
    RESOLUTIONS: (64, 64, 64, 64, 64, 64, 64, 64)
    USE_RASTERIZED_GT: False
    INV_SMOOTHNESS_SCHED: (0.1,)
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    PROPOSAL_ONLY_GT: False
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_NORM: 0.0
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  IMS_PER_BATCH: 16
  CLIP_GRADIENTS:
    ENABLED: False
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
VIS_PERIOD: 0
TEST:
  EVAL_PERIOD: 5000
