_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: True
  RESNETS:
    DEPTH: 101
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
  OPTIMIZER: "ADAM"
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_NORM: 0.0
  IMS_PER_BATCH: 16
  CLIP_GRADIENTS:
    ENABLED: False
INPUT:
  # Is this mandatory for 3x?
  DETR_STYLE_AUG: True
TEST:
  EVAL_PERIOD: 15000
