_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  ROI_MASK_HEAD:
    NAME: "BoundaryFormerPolygonHead"
    POOLER_TYPE: ""
  ROI_HEADS:
    NUM_CLASSES: 7
  BOUNDARY_HEAD:
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
    PRED_WITHIN_BOX: True
    POLY_NUM_PTS: 64
    CLS_AGNOSTIC_MASK: True
  DIFFRAS:
    RESOLUTIONS: (64, 64, 64, 64, 64, 64, 64, 64)
    USE_RASTERIZED_GT: False
    INV_SMOOTHNESS_SCHED: (0.01,)
  RESNETS:
    DEPTH: 50
INPUT:
  MIN_SIZE_TRAIN: (800,)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MAX_SIZE_TRAIN: 3000
  MIN_SIZE_TEST: 800
  MAX_SIZE_TEST: 3000
DATASETS:
  TRAIN: ("kins_2020_inmodal_instance_seg_train",)
  TEST: ("kins_2020_inmodal_instance_seg_val",)
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.0
  WEIGHT_DECAY_NORM: 0.0
  # ?
  STEPS: (20000, 22000)
  MAX_ITER: 24000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 4000
TEST:
  EVAL_PERIOD: 4000
