_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  ROI_HEADS:
    NUM_CLASSES: 7
  RESNETS:
    DEPTH: 50
INPUT:
  # KITTI images are quite small: ~12xx x 37x
  MIN_SIZE_TRAIN: (500, 532, 564, 596, 628, 660, 692, 724)
  MIN_SIZE_TRAIN_SAMPLING: "choice"
  MIN_SIZE_TEST: 500
  MAX_SIZE_TRAIN: 2398
  MAX_SIZE_TEST: 1656
DATASETS:
  TRAIN: ("kins_2020_inmodal_instance_seg_train",)
  TEST: ("kins_2020_inmodal_instance_seg_val",)
SOLVER:
  OPTIMIZER: "ADAM"
  BASE_LR: 1e-4
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.0
  WEIGHT_DECAY_NORM: 0.0
  STEPS: (18000,)
  MAX_ITER: 24000
  IMS_PER_BATCH: 8
  CHECKPOINT_PERIOD: 4000
TEST:
  EVAL_PERIOD: 4000
